import { NextRequest, NextResponse } from "next/server";
import { supabaseServer } from "@/kesimpulan-miniapp/lib/supabaseServer";

export async function POST(req: NextRequest) {
  try {
    const { imageDataUrl, summary } = await req.json();

    if (!imageDataUrl || typeof imageDataUrl !== "string") {
      return NextResponse.json(
        { error: "imageDataUrl is required" },
        { status: 400 }
      );
    }

    // --- decode dataURL ---
    const [meta, base64] = imageDataUrl.split(",");
    if (!base64) {
      return NextResponse.json(
        { error: "Invalid image data URL" },
        { status: 400 }
      );
    }

    const match = /data:image\/(png|jpeg|jpg);base64/.exec(meta);
    const ext = match?.[1] || "png";
    const buffer = Buffer.from(base64, "base64");

    const timestamp = Date.now();
    const imagePath = `images/kesimpulan-${timestamp}.${ext}`;

    // --- upload image ---
    const { error: uploadErr } = await supabaseServer.storage
      .from("kesimpulan")
      .upload(imagePath, buffer, {
        contentType: `image/${ext}`,
        upsert: false,
      });

    if (uploadErr) {
      console.error(uploadErr);
      return NextResponse.json(
        { error: "Failed to upload image" },
        { status: 500 }
      );
    }

    const { data: imagePublic } = supabaseServer.storage
      .from("kesimpulan")
      .getPublicUrl(imagePath);

    const imageUrl = imagePublic.publicUrl;

    // --- build metadata JSON ---
    const title =
      (summary || "Kesimpulan")
        .split(".")[0]
        .replace(/\n/g, " ")
        .slice(0, 80) || "Kesimpulan Visual";

    const metadata = {
      name: `Kesimpulan – ${title}`,
      description:
        "Visual summary generated by the Kesimpulan Farcaster mini app.",
      image: imageUrl,
    };

    const metadataPath = `metadata/kesimpulan-${timestamp}.json`;

    const { error: metaErr } = await supabaseServer.storage
      .from("kesimpulan")
      .upload(metadataPath, JSON.stringify(metadata), {
        contentType: "application/json",
        upsert: false,
      });

    if (metaErr) {
      console.error(metaErr);
      return NextResponse.json(
        { error: "Failed to upload metadata" },
        { status: 500 }
      );
    }

    const { data: metaPublic } = supabaseServer.storage
      .from("kesimpulan")
      .getPublicUrl(metadataPath);

    const tokenURI = metaPublic.publicUrl;

    return NextResponse.json({ tokenURI, imageUrl });
  } catch (e) {
    console.error(e);
    return NextResponse.json(
      { error: "Failed to process mint metadata" },
      { status: 500 }
    );
  }
}
